apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bbdms-web
  namespace: bbdms
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - bbdms.example.com
      secretName: bbdms-tls
  rules:
    - host: bbdms.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bbdms-web
                port:
                  number: 80
    - host: phpmyadmin.bbdms.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bbdms-phpmyadmin
                port:
                  number: 80

