apiVersion: v1
kind: Secret
metadata:
  name: bbdms-aws-secret
  namespace: bbdms
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: YOUR_AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: YOUR_AWS_SECRET_ACCESS_KEY

